### PR TITLE
Update apps.yaml

### PR DESCRIPTION
**Pull request by fduarte42**
New coffeBot app

### CODE REVIEW

**Comment by joerick** [comment]
@fduarte42 this is amazing!!! I'm going to post a few screenshots here

image image 
image
image
image
image

Quick summary- this app has a load of features that are really well thought through - my favourite thing is that many of these features have email hooks, so, for example, you can put a coffee on to brew, set a 5 minute timer and walk back to your desk, and get an email when it is done. 

Loads more stuff in there too, it looks like it must be super useful for your guys.

What's your setup look like? I'm guessing this is for an office kitchen environment? What are you  using for audio?

I have just one request - would you mind uploading a release of this with the .tingapp extension so Tide picks it up okay on Mac?

**Comment by fduarte42** [comment]
Cool that you like it. Yes we use it quite a lot in our office.

How do I do a release with tingapp extension? On macOS we did not use Tide because pygame is broken there and we could not start the emulator, but in PyCharm it work very well. We use the requirements-dev.txt there with added tingnbot-python and pygame. I saw a rendering bug for the order app that I will fix.

**Comment by joerick** [comment]
Yeah, looks like there's a bug in the pygame that's packaged into Tide on the Mac - seems to appear when using the audio functions of pygame. I can still upload the app to Tingbot using Tide though, so it would be good to have that compatibility.

It's just a matter of downloading the source you have and renaming the containing folder to .tingapp. Here's an example:

[coffeeBot.zip](https://github.com/tingbot/ocean/files/748137/coffeeBot.zip)

Then you can upload that zip to the release page on Github and they will host it for you :)

**Comment by fduarte42** [comment]
Please don't merge it yet! I will add the smtp settings to the settings.json in few minutes.

**Comment by joerick** [comment]
Ah, oops

**Comment by fduarte42** [comment]
ok I make a new pull request. ;-)

**Comment by fduarte42** [comment]
I did replace the old release. Please Merge my other pull request with the new zip_url

**Comment by fduarte42** [comment]
And we are using a bluetooth speaker behind the coffee machine for audio. ;-)

**Pull request merged**
