### PR TITLE
Update apps.yaml

### PR DESCRIPTION
**Pull request by codinghands**
Added in (amazingly, another!) SABnzbd management app

### CODE REVIEW

**Comment by joerick** [comment]
Nice app! I can't say I 100% understand it though! I'm guessing it's for a download manager?

**Comment by codinghands** [comment]
Thanks man! It is - SABnzbd is a NZB file downloader / manager - NZB being a package format for Usenet binary files - must be fairly popular amongst the KS crowd to have 2 within a fortnight of launch! Easy API and a nice lead in to bigger and better things :)

**Comment by joerick** [comment]
ahh. Usenet. Been a while since I went back there!

**Comment by codinghands** [comment]
Fun times! I just noticed installing my app on the device itself shows 'sabdash.tingapp' on the app launcher rather than a 'friendly' name - any idea how to fix?

**Comment by joerick** [comment]
The name comes from the `app.tbinfo` file. Just had a quick look at your and it looks like it's missing a comma, so I think the JSON isn't parsing. Fix that and it should format nicely :)

**Comment by codinghands** [comment]
Ah, fixed it now and it's all working great :)

**Pull request merged**
