### PR TITLE
Added "Adventure Time Giphy" to the ocean

### PR DESCRIPTION
**Pull request by omgmog**

### CODE REVIEW

**Comment by joerick** [comment]
😍

**Comment by joerick** [comment]
Hell yes I'm merging this!

**Comment by joerick** [comment]
Also, you're the first! Congrats. Any feedback on the process?

**Comment by omgmog** [comment]
Woop! 🎉 

Regarding the process:

Tingbot-python documentation was great. I imagine anybody with experience using Python (no matter how little) would be able to throw together a simple app as I have done.

For the pull request, anybody with experience using Github should be fine. If you've used Jekyll on Github Pages even more so. I figure the process is at a level of complexity that if you're writing programs in Python and hosting them on Github, you should be able to do this.

Cheers!

**Comment by joerick** [comment]
Thanks man, that's great to hear. Can't wait to see what you do next...

**Pull request merged**
