### PR TITLE
Added BeautifulTime

### PR DESCRIPTION
**Pull request by ghost**
Clock app focused on simple aesthetics.

### CODE REVIEW

**Comment by joerick** [comment]
Hey @WillManidis, nice app!

Couple things - could you move the `app.tbinfo` and `icon.png` files into the tingapp itself, and rename the tingapp from `main.tingapp` to `BeautifulTime.tingapp` so it's clear what the app's called when it's installed.

Don't forget to update the links in `apps.yaml`! Thanks.

**Comment by ghost** [comment]
Hey @joerick, Thank you!

I just made your requested changes, let me know if I did everything right.

**Comment by joerick** [comment]
Hey WillManidis - I checked your repo again at https://github.com/WillManidis/BeautifulTime, and it looks like you've got two folders that are tingapps, each with different case. Would you be able to merge these into just one folder? 

You might be able to do this by removing and readding the files with git.

(It's not a problem on Mac, because the file system is case-insensitive, but it will be a problem on other platforms)

**Comment by ghost** [comment]
Should be fixed now?

**Comment by joerick** [comment]
I sent you a PR - could you merge that then we should be good to go 👍

**Comment by ghost** [comment]
Merged! Thanks much

**Comment by joerick** [comment]
aaaaand you're up!

**Pull request merged**
