### PR TITLE
Merge remote-tracking branch 'tingbot/gh-pages' into gh-pages

### PR DESCRIPTION
**Pull request by fduarte42**
new release of the coffeeBot app

Bugfixes
30% less energy consumption
added animation to open/close app
MusicPlayer reads genres in mp3-files and the playlist can be filtered using them
MusicPlayer shows cover art, album and interpret information

### CODE REVIEW

**Comment by joerick** [comment]
hey fduarte42! I'm not seeing any changes on this PR... missing commit?

**Comment by fduarte42** [comment]
Hi,

i received the following error:


The page build completed successfully, but returned the following warning:

The CNAME `ocean.tingbot.com <http://ocean.tingbot.com/>` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken <https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken> for more information.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds <https://help.github.com/articles/troubleshooting-jekyll-builds>

**Comment by fduarte42** [comment]
now you should see the file change

**Comment by joerick** [comment]
Great! Got it. The page build error is because your fork is using branch gh-pages but can't push changes directly to ocean.tingbot.com.

**Pull request merged**
